/**
 * @openapply/shared-types
 * Shared TypeScript interfaces and JSON Schemas for OpenApply extension & monorepo.
 */

/**
 * Represents a parsed LinkedIn Job Posting listing.
 */
export interface LinkedInJobPosting {
  jobId: string;
  /** SHA-256 or hash of job_id for quick local deduplication */
  jobHash: string;
  title: string;
  company: string;
  location: string;
  isRemote: boolean;
  applicantCount: number;
  isPromoted: boolean;
  description: string;
  postedDate?: string;
  url: string;
  scrapedAt: string;
}

/**
 * Risk tier level for fake remote job listings.
 */
export type FakeRemoteRisk = 'LOW' | 'MEDIUM' | 'HIGH';

/**
 * Comprehensive job evaluation scorecard generated by ATS engine.
 */
export interface JobScorecard {
  jobId: string;
  /** ATS fit score scaled from 0 to 100 */
  overallScore: number;
  keyMatchingSkills: string[];
  missingSkills: string[];
  fakeRemoteRisk: FakeRemoteRisk;
  fakeRemoteReasons: string[];
  summary: string;
  tailoredCoverLetter?: string;
  evaluatedAt: string;
}

/**
 * Candidate profile resume schema for tailoring applications.
 */
export interface UserResume {
  fullName: string;
  email: string;
  phone?: string;
  location: string;
  summary: string;
  skills: string[];
  workHistory: Array<{
    company: string;
    role: string;
    duration: string;
    highlights: string[];
  }>;
  education: Array<{
    institution: string;
    degree: string;
    year: string;
  }>;
  targetRoles: string[];
  customInstructions?: string;
}

/**
 * Unemployment application status progression state.
 */
export type ApplicationStatus = 'Applied' | 'Screening' | 'Interviewing' | 'Rejected' | 'Offer';

/**
 * Unemployment log entry for state claim audit tracking.
 */
export interface UnemploymentLogEntry {
  id: string;
  /** ISO format YYYY-MM-DD */
  dateApplied: string;
  company: string;
  jobTitle: string;
  location: string;
  workType: 'Remote' | 'Hybrid' | 'On-site';
  jobUrl: string;
  jobId: string;
  /** Unique application proof code */
  confirmationNumber: string;
  status: ApplicationStatus;
  notes?: string;
  syncedToDrive: boolean;
  syncedAt?: string;
}

/**
 * Supported AI engine providers for BYOK requests.
 */
export type AIProvider = 'openai' | 'gemini' | 'custom';

/**
 * User configuration settings schema for OpenApply extension.
 */
export interface OpenApplySettings {
  apiKey: string;
  provider: AIProvider;
  model: string;
  customEndpoint?: string;
  autoFilterPromoted: boolean;
  /** Default threshold count (e.g. 100) above which listings are dimmed */
  maxApplicantThreshold: number;
  hideFakeRemote: boolean;
  autoSyncDrive: boolean;
  driveFolderId?: string;
  googleOAuthConnected: boolean;
  userEmail?: string;
  /** State claim logging format code (e.g. 'CA', 'TX', 'NY') */
  unemploymentStateCode?: string;
}

/**
 * Extension Chrome Storage state schema.
 */
export interface ChromeStorageData {
  settings?: OpenApplySettings;
  userConfig?: OpenApplyUserConfig;
  resume?: UserResume;
  unemploymentLogs?: UnemploymentLogEntry[];
  scorecards?: Record<string, JobScorecard>;
}

/**
 * First-time onboarding, preferences, BYOK, and analytics configuration schema.
 */
export interface OpenApplyUserConfig {
  onboardingCompleted: boolean;
  preferences: {
    hidePromotedJobs: boolean;
    hideHighApplicantJobs: boolean;
    maxApplicantThreshold: number;
  };
  aiProvider: {
    providerId: 'openai';
    apiKey: string;
    isValidated: boolean;
  };
  analytics: {
    optIn: boolean;
    clientId: string;
  };
}

/**
 * Default fallback user configuration values.
 */
export const DEFAULT_USER_CONFIG: OpenApplyUserConfig = {
  onboardingCompleted: false,
  preferences: {
    hidePromotedJobs: true,
    hideHighApplicantJobs: true,
    maxApplicantThreshold: 50
  },
  aiProvider: {
    providerId: 'openai',
    apiKey: '',
    isValidated: false
  },
  analytics: {
    optIn: false,
    clientId: ''
  }
};
